spring.application.name=backend
server.port=8085

# H2 Configuration
spring.datasource.url=jdbc:h2:mem:logforxdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# JPA Setup
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Increase Upload Limits for Forensics
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
